CREATE TABLE article (
    id              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            varchar(255),
    description     clob,
    created_at      timestamp NOT NULL,
    updated_at      timestamp NOT NULL,
    CONSTRAINT pk_article PRIMARY KEY (id)
);